#!/bin/sh
### BEGIN INIT INFO
# Provides: udpclient
# Required-Start: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO
case "$1" in
  start) /usr/bin/udpclient &;;
  stop) pkill -f /usr/bin/udpclient;;
  *) echo 'Usage: $0 {start|stop}'; exit 1;;
esac
